# Python/Django Installation
FROM python:3.6

# Redirects StdOut
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt .

RUN pip3 install --upgrade pip --no-cache-dir -r requirements.txt

# File Installation
COPY .  /app/

# Set the Django configuration to frontend-dev
RUN mv ./phutball/config/settings_frontend_dev.py ./phutball/config/config.py
