# Generated by Django 3.0.6 on 2020-05-05 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('player_0_name', models.CharField(default='Player 1', max_length=30)),
                ('player_1_name', models.CharField(default='Player 2', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('board_state', models.CharField(default='                                                                                                                                              O                                                                                                                                              ', max_length=285)),
                ('move_num', models.PositiveSmallIntegerField()),
                ('ai_move', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Game')),
            ],
        ),
    ]
