# Generated by Django 3.0.6 on 2020-05-06 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('player_0_name', models.CharField(default='Player 1', max_length=30)),
                ('player_1_name', models.CharField(default='Player 2', max_length=30)),
                ('ai_player', models.BooleanField(default=False)),
                ('ai_player_num', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('board_state', models.CharField(default='                                                                                                                                              O                                                                                                                                              ', max_length=285)),
                ('move_num', models.PositiveSmallIntegerField(default=0)),
                ('move_str', models.CharField(default='Reset', max_length=570)),
                ('ball_loc_letter_index', models.SmallIntegerField(default=7)),
                ('ball_loc_number_index', models.SmallIntegerField(default=9)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Game')),
            ],
        ),
    ]
