# Generated by Django 3.0.6 on 2020-05-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ai_player',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='ai_player_num',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
