# Generated by Django 3.0.6 on 2020-05-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200517_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ai_player',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='ai_player_num',
            field=models.BooleanField(default=False),
        ),
    ]
